---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: exampleSite/data/homepage.yml
  label: Startseite
- type: heading
  label: Projekte
- type: document
  path: exampleSite/content/bauprojekt/_index.md
  label: Projektseite
- type: directory
  path: exampleSite/content/bauprojekt
  label: Projekt
  create: documents
  match: "*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Referenzen
- type: document
  path: exampleSite/content/referenzen/_index.md
  label: Referenzseite
- type: document
  path: exampleSite/data/portfolio.yml
  label: Referenz Daten
- type: heading
  label: Über Uns
- type: document
  path: exampleSite/content/ueber-uns/_index.md
  label: Über Uns Seite
- type: document
  path: exampleSite/data/about.yml
  label: Über Uns Daten
- type: heading
  label: Weitere Seiten
- type: directory
  path: exampleSite/content/kontakt
  label: Kontakt, Impressum, Datenschutz
  create: none
  match: "*"
  exclude: _index.md
- type: heading
  label: Konfiguration
- type: directory
  path: exampleSite
  label: Konfiguration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.72.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
