# default configuration
baseURL = "https://krdesign-wohnen.yotequiero.de"
languageCode = "de-DE"
summaryLength = "10"
theme = "KRDesignWohnen"
title = "K & R Design und Wohnen GmbH"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[menu]
#[[menu.main]]
#URL = "about"
#name = "Über Uns"
#weight = 1

[[menu.main]]
URL = "blog"
name = "Projekte"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Referenzen"
weight = 3

#[[menu.main]]
#URL = "contact"
#name = "Kontakt"
#weight = 4

[[menu.main]]
URL = "legal/impressum"
name = "Impressum"
weight = 5


# default parameters
[params]
home = "Start"
logo = "images/logo.png"
logo_alt = "images/illustrations/logo_wte.png"

# theme color
#ligt theme
theme_backgroundcolor = "#fff"
theme_backgroundcontrastcolor = "#eaeaea"
#theme_color = "#c6a47e"
theme_color = "#E6D9C8"
#theme_contrastcolor = "#4974a5"
theme_contrastcolor ="#908071"
theme_textcolor = "#4c4c4c"
theme_lightcolor = "#999"
theme_darkcolor = "#222"
#dark theme
#theme_backgroundcolor = "#282d32"
#theme_backgroundcontrastcolor="#cdcdcd"
#theme_color = "#282d32"
#theme_contrastcolor = "#c6a47e"
#theme_textcolor = "#ffffff"
#theme_lightcolor = "#cdcdcd"
#theme_darkcolor = "#212529"

# contact info
phone = "<a class='text-white' href='tel:+491723516360'>Uwe Riedel: 0172 351 6360</a><br/><a class='text-white' href='tel:+4915255375489'>Maik Kotas: 01525 537 5489</a>"
email = "info@krdesign-wohnen.de"
address = "Körnerplatz 1<br/>01326 Dresden"
# meta description
author = "Uwe Riedel"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020"
legal1 = "Impressum"
legal2 = "Datenschutz"


# contact
[params.contact]
enable = false
title = "Kontaktformular"
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = false
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"